language: ruby
sudo: false
rvm:
- 2.6.2
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
script: bundle exec rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  slack:
    secure: nRwoGCkm4covxolK9ralBPCHkHmAG7ICANiH0WgBm95HmYxLA71ObktGziwzEr6OvJrrRy79ZtWTG6BT1WcdVjomxsSK/GANareDTAHsXZ+wa4YrspC++nZx5xXopGJEgO/rr2ZKbO63gVCjiH3b3kUm3R47EBd0CQrExNgw5XkBxdRmtPAGknRm3EshhQ9yEt9ytr4w51ssfinGTh1df97eXsRp2iuCwuVI/FvIMcV0x7BNi6aYzQILFbny3QUjDaMOxfo8R42hbNR7XlaKx2v1ugSWqOJA1E+r89HSBZkpF2iaPO9wh2ctxK4WS4BOiU7toOt+ulu6uz83i1sFYCjQPuD0itzSqNZj33QecN5bE03y3TKHLe4w4hJLIkfBfWdfJYLv9w+MFaZFz3T6Z/evL323BKr5Vq7BWeljuEqNQoHYzjgWCmsHF5DdGvQ4ceYihJdTr6xi/KTi0VaT9UlhNtLI8/vs7YyVmxMRwie5pcW5WqqBVXG8cqpZf76X2qQzsejP/I4plqNeQw1vUrhZWeMx8DlQN4hODxMi5M63O613UwJJxvuak0PAjmmAV0O1f7oAd6ZzdEwtCwiaJqsTVEplYgPqwNKnTzQbUS0DvxKNazfMGi+vNPdAHeS7BE22mkLbF3O2U68WjZ8wF/faMCvrFqWU55AJuk4fGgk=
